/* DO NOT EDIT THIS FILE */
package com.hapz.assessment.model;

import javax.persistence.*;

@Entity
public class SearchCacheMovie {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String movieTitle;

    public SearchCacheMovie() {
    }

    public SearchCacheMovie(String movieTitle) {
        this.movieTitle = movieTitle;
    }

    public Long getId() {
        return id;
    }

    public String getMovieTitle() {
        return movieTitle;
    }

    public void setMovieTitle(String movieTitle) {
        this.movieTitle = movieTitle;
    }
}
